version: '3.8'
services:
  base.api:
    container_name: OrderStore
    build:
       context: .
       dockerfile: Core/Base/Dockerfile
    environment:
        - ASPNETCORE_URLS = http://localhost:5001
        - PathBase = http://localhost:5001
        - ConnectionString = Server=127.0.0.1;User Id=sa;Password=yourStrong1234567890!Password;Database=BikeStores;TrustServerCertificate=True;
    depends_on:
        - db
    ports:
        - 5001:5001 

  db:
    build: ./DbConfig
    ports:
        - 1433:1433

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1